### ISSUE TITLE
svg with no width and height attributes are not rendered

### ISSUE THREAD

**Issue by lexboss777** [pltxtra/libsvgandroid#5]
Hi!
If svg has no width and height attributes it's not rendered. Those svg's has viewBox attribute though, and rendered fine with other libs

**Comment by lexboss777** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128" enable-background="new 0 0 128 128"><path fill="#fff" d="M116 0h-104c-6.6 0-12 5.4-12 12v104c0 6.6 5.4 12 12 12h104c6.6 0 12-5.4 12-12v-104c0-6.6-5.4-12-12-12z"/><g fill="#7F7F7F"><path d="M105.2 33.3h-57.7l-2-2.4c-1-1.2-2.4-1.8-3.9-1.8h-17.1c-2.8 0-5.1 2.3-5.1 5.1v60.3c0 2.8 2.3 5.1 5.1 5.1h80.7c2.8 0 5.1-2.3 5.1-5.1v-56c0-3-2.2-5.2-5.1-5.2zm2.6 61.1c0 1.4-1.2 2.6-2.6 2.6h-80.7c-1.4 0-2.6-1.2-2.6-2.6v-60.3c0-1.4 1.2-2.6 2.6-2.6h17.2c.8 0 1.5.3 2 .9l4.8 5.8c1.4 1.8 3.6 2.8 5.9 2.8h51c1.4 0 2.6 1.2 2.6 2.6l-.2 50.8zm0-55.3c-.8-.4-1.7-.7-2.6-.7h-51c-1.5 0-2.9-.7-3.9-1.8l-.7-.8h55.6c1.4 0 2.6 1.2 2.6 2.6v.7zM116 2c5.5 0 10 4.5 10 10v104c0 5.5-4.5 10-10 10h-104c-5.5 0-10-4.5-10-10v-104c0-5.5 4.5-10 10-10h104m0-2h-104c-6.6 0-12 5.4-12 12v104c0 6.6 5.4 12 12 12h104c6.6 0 12-5.4 12-12v-104c0-6.6-5.4-12-12-12z"/></g></svg>`

**Comment by pltxtra** [comment]
Hi, did you use SvgRaster.svgAndroidRender() or SvgRaster.svgAndroidRenderToArea()? I have corrected a bug in the latter. Previously it could not properly render your example. After the patch both methods should work.

**Comment by lexboss777** [comment]
I did use SvgRaster.svgAndroidRenderToArea().
Thanks for patch.
I did a little hotfix myself, though) Ofcourse it's not elegant. Just wanted it to work.
I am not a C developer. I use binding of your lib to C#.

svg_group.c-->_svg_group_apply_svg_attributes
```
if (view_box_str)
    {
	    (void) _svg_element_parse_view_box (view_box_str,
		    			      &group->view_box.box.x,
		    			      &group->view_box.box.y,
		    			      &group->view_box.box.width,
		    			      &group->view_box.box.height);

	_svg_length_init(&group->width, group->view_box.box.width);   // added this line
	_svg_length_init(&group->height, group->view_box.box.height); // and this line
```
